const LOAD_MOVIE = "LOAD_MOVIE";
const SET_MOVIES = "SET_MOVIES";
const LOAD_RANDOM = "LOAD_RANDOM";
const SET_RANDOM = "SET_RANDOM";
const LOAD_SELECTED = "LOAD_SELECTED";
const SET_SELECTED = "SET_SELECTED";
const SET_CURRENTPAGE = "SET_CURRENTPAGE";
const SET_TOTALPAGES = "SET_TOTALPAGES";
const LOAD_SEARCH = "LOAD_SEARCH";
const SET_SEARCH = "SET_SEARCH";
const SET_SORTFIELD = "SET_SORTFIELD";
const SET_MOVIETYPE = "SET_MOVIETYPE"
export {
  SET_MOVIETYPE,
  SET_SORTFIELD,
  SET_TOTALPAGES,
  SET_CURRENTPAGE,
  LOAD_MOVIE,
  SET_MOVIES,
  LOAD_RANDOM,
  SET_RANDOM,
  LOAD_SELECTED,
  SET_SELECTED,
  LOAD_SEARCH,
  SET_SEARCH,
};
